// Custom Font Generated from: FATPIXEL.TTF
// Font Size: 16px
// Generated by convert_font.py

#ifndef FATPIXEL_FONT_H
#define FATPIXEL_FONT_H

#include <stdint.h>
#include <Adafruit_GFX.h>

// Font information
#define FONT_SIZE 16
#define FONT_CHAR_COUNT 89

// Character data structure
typedef struct {
    uint16_t width;
    uint16_t height;
    const uint16_t* data;
} FontChar;

// Font data
extern const FontChar customFont[FONT_CHAR_COUNT];

// Function declarations
int getCharIndex(char c);
void drawFatpixelChar(Adafruit_GFX* display, char c, int x, int y, uint16_t color);
void drawFatpixelText(Adafruit_GFX* display, const char* text, int x, int y, uint16_t color);

#endif // FATPIXEL_FONT_H
